stages:
  preprocessing:
    cmd: python preprocessing.py
    deps:
    - preprocessing.py
    - data/data_raw
    outs:
    - data/data_processed
  train:
    cmd: python train.py
    deps:
    - train.py
    - data/data_processed
    outs:
    - confusion_matrix.png
    metrics:
    - metrics.json:
        cache: false