stages:
  get_data:
    cmd: python get_data.py
    deps:    
    - get_data.py
    - scripts/get_data.sh
    outs:
    - data/data_raw/data_raw.csv  
  preprocessing:
    cmd: python preprocessing.py
    deps:
    - preprocessing.py
    - data/data_raw/data_raw.csv  
    outs:
    - data/data_processed/data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data/data_processed/data_processed.csv
    outs:
    - confusion_matrix.png
    metrics:
    - metrics.json:
        cache: false