name: ci
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Actions Libraries
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3   
      - uses: iterative/setup-cml@v1

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train.py

      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          echo "## Metrics"
          #echo "![](./confusion_matrix.png)" >> report.md
          cml comment create report.md  