name: ci-pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    #optionally use a convenient Ubuntu LTS + DVC + CML image
    #container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4   
      - uses: iterative/setup-cml@v1

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Preprocessing
        run: |
          python src/preprocessing.py    

      - name: Train Model
        run: |
          python src/train.py

      - name: Report - DVC Compare
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |       

          dvc repro

          echo "## Metrics" >> report.md
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff --show-md main > report.md

          #echo "## Plots" >> report.md      
         # echo "![](./confusion_matrix.png)" >> report.md
          cml comment create report.md