name: ci-pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    #optionally use a convenient Ubuntu LTS + DVC + CML image
    #container: ghcr.io/iterative/cml:0-dvc2-base1
    container: docker://dvcorg/cml-py3:latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3   
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-tools@v1

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Preprocessing
        run: |
          python src/preprocessing.py    

      - name: Train Model
        run: |
          python src/train.py

      - name: Report DVC
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |       

          echo "## Params" >> report.md

          cat reports/params/params.json >> report.md

          echo "## Metrics" >> report.md

          cat reports/metrics/metrics.json >> report.md

          echo "## Plots" >> report.md

          echo "![](reports/plots/confusion_matrix.png)" >> report.md


          cml comment create report.md