name: Run code
on:
  push: 
    branches:
     - main
    paths:
      - config/**
      - src/**
      - data/*
      - .github/workflows/dvc_pull.yaml
jobs:
  run_code:
    name: Run code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repository
        id: checkout
        uses: actions/checkout@v2

      - name: Pull data from DVC
        run: |
          dvc pull
      - name: Run the pipeline with DVC
        run: dvc repro
          